### PR TITLE
Fix issue introduced by #13512

### LINKED ISSUE #13973: Upgrading from 3.13.x to 4.x breaks management UI
### Describe the bug

Upgrading a 3.13.x system to 4.x with your system theme set to dark causes the management UI to cease working.

### Reproduction steps

1. Clear your browser cache to start fresh.
2. Enable your system's dark theme (optional)
3. Start RabbitMQ 3.13.x and log into the management UI.
4. Stop RabbitMQ 3.13.x, and start RabbitMQ 4.x.
5. Return to the management UI and refresh/force-refresh it.
6. Once refreshed, the UI ceases to work and the dev tools shows the following error:
    ```
    content_script.js:1 content script loaded 38f38f44-a4a1-445f-b3a0-fb06aafaafae
    credentials.js:1 Injecting credentials patch
    sammy-0.7.6.min.js:5 [Wed May 28 2025 10:48:40 GMT-0700 (Pacific Daylight Time)] body Plugin Error: called use() but plugin (Sammy.Title) is not defined Cannot read properties of undefined (reading 'apply') TypeError: Plugin Error: called use() but plugin (Sammy.Title) is not defined Cannot read properties of undefined (reading 'apply')
        at Sammy.Application.use (sammy-0.7.6.min.js:5:7826)
        at Sammy.Application.dispatcher (main.js:77:10)
        at new Sammy.Application (sammy-0.7.6.min.js:5:6748)
        at start_app (main.js:197:11)
        at dispatcher_add (main.js:72:9)
        at dispatcher.js:1:1
    main.js:78 Uncaught TypeError: this.setTitle is not a function
        at Sammy.Application.dispatcher (main.js:78:10)
        at new Sammy.Application (sammy-0.7.6.min.js:5:6748)
        at start_app (main.js:197:11)
        at dispatcher_add (main.js:72:9)
        at dispatcher.js:1:1
    ```
7. After the above happens, you are unable to do anything in the management UI. Only clearing the cache resolves the issue. Thankfully, that appears to _permanently_ resolve the issue. Running the UI in a private/incognito window also works, presumably because assets are not cached.

### Expected behavior

Upgrading from 3.13.x to 4.x does not compromise the behavior of the management UI.

### Additional context

Related issues:
* https://github.com/rabbitmq/rabbitmq-server/pull/13512

### PR DESCRIPTION
**Pull request by lukebakken**
Moves Sammy.Title plugin into its own file.

Fixes #13973

### CODE REVIEW

**Comment by lukebakken** [comment]
This appears to fix the issue after upgrade, but then it seems like light/dark mode isn't immediately applied until a refresh happens 🤔

**Comment by ikavgo** [comment]
I like it. In my Web days we did concatenation + compaction + hash in the name - no chances to suffer from cache unless html page itself cached.

**Comment by michaelklishin** [comment]
@lukebakken until an automatic (every 5s by default) refresh happens? Does it mean the user has to wait for 5s once after upgrading and then the selected team applies?

**Comment by lukebakken** [comment]
> until an automatic (every 5s by default) refresh happens? Does it mean the user has to wait for 5s once after upgrading and then the selected team applies?

I just re-tested an upgrade from 3.13.x -> 4.0.x -> 4.1.x (broken UI) -> `main` (with my patch) and a refresh / force-refresh is _not_ necessary. That must have been due to me skipping intermediate versions.

**Review by michaelklishin — APPROVED** [review]
